### ISSUE TITLE
Clicking "edit this page" on https://pnpm.io/motivation redirects to 404 on github

### ISSUE THREAD

**Issue by cschar** [pnpm/pnpm.io#156]
steps to reproduce:

- navigate to https://pnpm.io/motivation
- click 'edit this page'
clicking the link leads to here

https://github.com/pnpm/pnpm.github.io/edit/main/versioned_docs/version-6.x/motivation.md

**Comment by zkochan** [comment]
This happens because the `versioned_docs/version-6.x` directory is just copied from the `docs` directory.

**Comment by juanpicado** [comment]
I see, only `next` works  https://pnpm.io/next/motivation. The directory 6.x is not being committed but 5.x is, any context why?

**Comment by zkochan** [comment]
because 6.x and next is the same. So to reduce duplication, 6.x is copied from next

**Comment by cschar** [comment]
closing as resolved

**Comment by melroy89** [comment]
its again happening: https://github.com/pnpm/pnpm.io/issues/649
