### ISSUE TITLE
On version page release notes buttons redirects to 404.

### ISSUE THREAD

**Issue by darkRaspberry** [pnpm/pnpm.io#380]
### What's the issue

On page https://pnpm.io/versions the release notes button redirects to 404 page due to error in repo url in line 46

https://github.com/pnpm/pnpm.github.io/blob/8313a72b486581aa80ef2336411c786accf2f18e/src/pages/versions.js#L46

### what's need to be fixed.
 - the repoUrl in line 46 is not correctly refer to pnpm repo, but refer to docs repo.
 - because of repoUrl the current version is also not able to render which gives that url on the website that goes to 404 page.

Fixing the repo url fixes the version no and it fixes all the issue related to.

The repo url after render is `https://github.com/pnpm/pnpm.github.io/releases/tag/v7.x`
But it should render like this `https://github.com/pnpm/pnpm/releases/tag/v7.26.0`

**Comment by zkochan** [comment]
How have you found that page at all? There are no links leading to it.

**Comment by darkRaspberry** [comment]
Well, I don't actually remember now, I was searching docs for questions, and used google search maybe then I found it.

**Comment by jameswomack** [comment]
I experienced this issue today as well. It's discoverable by searching something like "pnpm stable version" with Google.
