### ISSUE TITLE
[doc] installation script titled "On Alpine Linux" should be titled "In docker container and Dockerfile"

### ISSUE THREAD

**Issue by ZYinMD** [pnpm/pnpm.io#477]
### Contribution

- [X] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))
(But I couldn't find the source code of the doc)

### Describe the user story

In doc > Introduction > Installation, the POSIX installation script doesn't work in docker container or Dockerfile, **not just in Alpine**, but in other type of images too.

For instance:
```bash
docker run -it --rm node:latest bash
wget -qO- https://get.pnpm.io/install.sh | sh - #  ERR_PNPM_UNKNOWN_SHELL
```
```bash
docker run -it --rm python:latest bash
wget -qO- https://get.pnpm.io/install.sh | sh - #  ERR_PNPM_UNKNOWN_SHELL
```
```bash
docker run -it --rm ubuntu:latest
apt update && apt install -y wget
wget -qO- https://get.pnpm.io/install.sh | sh - #  ERR_PNPM_UNKNOWN_SHELL
```

### Describe the solution you'd like

The [On Alpine Linux](https://pnpm.io/installation#on-alpine-linux) section title should be named "In docker container and Dockerfile".

### Describe the drawbacks of your solution

Maybe there are a small number of people who are really using the Alpine Linux, but not with docker? But (1) there can't be many (2) the POSIX script might just work for them (3) the benefit outweighs risk

### Describe alternatives you've considered

Better handle the ERR_PNPM_UNKNOWN_SHELL error in the POSIX script.

**Comment by KSXGitHub** [comment]
Mentioning both "docker container" and "dockerfile" would be redundant. Just one is sufficient.

Anyway, just make a PR and @zkochan will discuss it with you further.
