### ISSUE TITLE
Incorrect link in docs

### ISSUE THREAD

**Issue by deadcoder0904** [pnpm/pnpm.io#510]
It looks like it should be linked to https://origin.nodejs.org/en/docs/guides/nodejs-docker-webapp

Currently, its linked to https://nodejs.org/en/docs/guides/nodejs-docker-webapp/

The page in question -> https://pnpm.io/cli/fetch

**Comment by lietsondsantos** [comment]
There has been an update to the Node.js page. I think because of this some links broke.

The page referenced in the documentation I think would be this: https://github.com/nodejs/docker-node

Right?

**Comment by zkochan** [comment]
Thanks
