### ISSUE TITLE
outdated actions/setup-node@v2 uses unsupported node12

### ISSUE THREAD

**Issue by MikeMcC399** [pnpm/pnpm.io#560]
## Issue

https://pnpm.io/continuous-integration#github-actions contains a note

> Caching packages dependencies with actions/setup-node@v2 requires you to install pnpm with version 6.10+.

[actions/setup-node@v2](https://github.com/actions/setup-node/tree/v2) uses `node12` which is no longer supported.
[actions/setup-node@v3](https://github.com/actions/setup-node/tree/v3) uses `node16` which is no longer supported.
[actions/setup-node@v4](https://github.com/actions/setup-node/tree/v4) uses `node20`. This is the current supported version.

## Reference

https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

Following on from our [warning in workflows using Node16](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/) we will start enforcing the use of Node20 rather than Node16 on the 3rd of June (2024).

What you need to do
For Actions maintainers: Update your actions to run on Node20 instead of Node16 ([Actions configuration settings](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-javascript-actions))
For Actions users: Update your workflows with latest versions of the actions which runs on Node20 ([Using versions for Actions](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions))

## Suggestion

Probably the reference to [actions/setup-node@v2](https://github.com/actions/setup-node/tree/v2) can be removed from https://pnpm.io/continuous-integration#github-actions

**Comment by MikeMcC399** [comment]
Please let me know if you would like a PR to delete the outdated section.

**Comment by zkochan** [comment]
This was updated I believe

**Comment by MikeMcC399** [comment]
@zkochan 

The note I was referring to is still there on the website:

![image](https://github.com/user-attachments/assets/1ec3ff18-47ce-43f8-9278-bd0007e03e6d)
